name: epub
version: 1.2.9
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Web or in Flutter 
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
dependencies:
  async: "^2.2.0"
  archive: "^2.0.8"
  xml: "^3.4.1"
  image: "^2.0.7"
dev_dependencies:
  path: "^1.6.2"
